#104392 add ignore commands, fix jobs metric, add status label to kaf…
ensi-platform/laravel-metrics pull request #8
Opened 2023-09-29 14:30 UTC by Farrukh00-coder

…ka metrics

2023-09-29 15:01 UTC, Farrukh00-coder commented
Так как новый лейбл добавляется к старой метрике. То часть значений у данной метрики будет содержать новый лейбл, а часть нет. Из-за такой ситауции метод получения метрик будет падать, так как пакет(https://github.com/PromPHP/prometheus_client_php) он не расчитан на это. Решили эту проблему след образом:
1) отгрузить старый код отключив метрики
2) удалить врунчую метрики из редиса
3) отгрузить новый код включив метрики, тогда оно будет писать в пустой редис и не упадёт

Так как это открытый пакет, то может при создании тега оставить коммент, чтоб при обновлении пакета люди понимали, что такая проблема может возникнуть

2023-10-02 12:57 UTC, MadridianFox commented
> Так как новый лейбл добавляется к старой метрике. То часть значений у данной метрики будет содержать новый лейбл, а часть нет. Из-за такой ситауции метод получения метрик будет падать, так как пакет(https://github.com/PromPHP/prometheus_client_php) не расчитан на это. Решили эту проблему след образом:
> 
> 1. отгрузить старый код отключив метрики
> 2. удалить врунчую метрики из редиса
> 3. отгрузить новый код включив метрики, тогда оно будет писать в пустой редис и не упадёт
> 
> Так как это открытый пакет, то может при создании тега оставить коммент, чтоб при обновлении пакета люди понимали, что такая проблема может возникнуть?

1) никто не читает ченджлоги при обновлении пакетов, люди просто делают composer update и верят что автор пакета ничего не сломает в обновлении
2) даже если мы как-то донесём до людей, что нужно отгружать правки особым образом, мы всё ещё доставим им неудобства, т.к. вынудим проводить довольно сложную отгрузку
3) если бы это было в рамках одного проекта и один раз, то можно было бы вручную удалять метрики, но у нас нет гарантии, что в будущем ситуация не повторится, так что нужно искать способ обойти проблему

Предлагаю поискать способ обнаружить и обработать эту ситуацию. Наверное допустимо будет в случае несоответствия количества лейблов удалять из редиса данные по этой метрике и записывать новые, уже без конфликта.
В крайнем случае можно сделать форк пакета чтобы досталять неудобство только своему проекту.

2023-10-02 13:03 UTC, MadridianFox requested changes
.

2023-10-03 06:34 UTC, Farrukh00-coder commented
Убрал добавление нового лейбла для кафки. Статус ответа консюмеров кафки буду делать в рамках новой задачи(https://redmine.greensight.ru/issues/114765)

2023-10-03 07:06 UTC, MadridianFox approved these changes

2023-10-03 07:16 UTC, merged